#Installing the packages from CRAN
install.packages("tidyverse")
install.packages("dplyr")
install.packages("ggplot2")    
install.packages("stringr")
install.packages("writexl")
#Loading the packages into this project
library(ggplot2)
library(dplyr)
library(tidyverse)
library(readxl)
library(stringr)
library(writexl)
library(rstatix)
set.seed(1)

#Loading the dataset
dataframe <- read_excel("/Users/yashkarnik/Desktop/University of Surrey/Dissertation/Dataset for Tableau & R.xlsx")

# Dataset cleaning
# Removing unnecessary columns from the dataset
newdataframe = subset(dataframe, select = -c(`Date of Survey`, `start`, `end`, `Date of Survey`, `Part 1 Background`, `Part B: Licensing/Technology General`, `Part 3: Innovation and Sources of Knowledge`, `Part 4: Networking and Knowledge Flows`, `_id`, `_uuid`, `_submission_time`, `_validation_status`, `_notes`, `_status`, `_submitted_by`, `_tags`, `_index`))
dataframe <- newdataframe
view(dataframe)

#Creating a new dataframe 
df <- dataframe

#To know the number of observations
dataframe %>%
  summarise(observations = n())

#To examine the dataframe
dim(dataframe)
str(dataframe)
head(dataframe)
tail(dataframe)

#Tranforming Age into ordinal values
dataframe$Age1 <- dataframe$Age

dataframe$Age1 <- str_replace_all(dataframe$Age1, "15-25", "Young Adults")
dataframe$Age1 <- str_replace_all(dataframe$Age1, "26-35", "Early Professionals")
dataframe$Age1 <- str_replace_all(dataframe$Age1, "36-45", "Middle Aged Professionals")
dataframe$Age1 <- str_replace_all(dataframe$Age1, "46-60", "Experienced Professionals")
dataframe$Age1 <- str_replace_all(dataframe$Age1, "60+", "Elderly")

view(dataframe$Age1)


#Tranforming Number of Years in Mining into categories
Experience_in_mining <- dataframe$`Number of years in mining`
Experience_in_mining_num <- as.numeric(Experience_in_mining)
class(Experience_in_mining_num)

df$Experience <- Experience_in_mining_num


Experience_in_mining <- dataframe$`Number of years in mining`

df["Experience"] = cut(df$Experience, c(0, 5, 11, 16, 22, 28, 34, Inf), c("0-5", "6-11", "12-16", "17-22", "23-28", "29-34", "35+"), include.lowest=TRUE)

# Assigning weights to qualitative columns
df$Barriers1 <- dataframe$`Barriers for not getting a license`
df$Barriers1 <- str_replace_all(df$Barriers1, "Not applicable", "0")
df$Barriers1 <- str_replace_all(df$Barriers1, "Bureaucracy", "1")
df$Barriers1 <- str_replace_all(df$Barriers1, "Bureaucracy & Others", "2")
df$Barriers1 <- str_replace_all(df$Barriers1, "Bureaucracy & Unaware about the requirements", "3")
df$Barriers1 <- str_replace_all(df$Barriers1, "Costs", "4")
df$Barriers1 <- str_replace_all(df$Barriers1, "Costs & Bureaucracy", "5")
df$Barriers1 <- str_replace_all(df$Barriers1, "Costs & Other", "6")
df$Barriers1 <- str_replace_all(df$Barriers1, "Costs & Unaware about the requirements", "7")
df$Barriers1 <- str_replace_all(df$Barriers1, "Not eligible", "8")
df$Barriers1 <- str_replace_all(df$Barriers1, "Other", "9")
df$Barriers1 <- str_replace_all(df$Barriers1, "Other & Unaware about the requirements", "10")
df$Barriers1 <- str_replace_all(df$Barriers1, "Unaware about the requirements", "11")


#(1)Trying Chi square test on Mining License v/s Education
#Creating a new variable that stores the values of 'Level of Education' & 'Mining License' and converting it to a factor
Education_factor <- factor(c(df$`Level of Education`))
Mining_License_factor <- factor(c(df$`Mining License`))

class(Mining_License_factor) #Checking the class of Mining License
class(Education_factor) #Checking the class of Education variable

#Checking number of levels created
nlevels(Education_factor)
nlevels(Mining_License_factor)

#Viewing the levels created
levels(Education_factor)
levels(Mining_License_factor)

# Creating a separate data frame
Mining_license_vs_Education_df = data.frame(Education_factor, Mining_License_factor)
# Creating a contingency table
Mining_license_vs_Education_table = table(Education_factor, Mining_License_factor) 
print(Mining_license_vs_Education_table )

#Setting the graph margins
par("mar")
par(mar=c(1,1,1,1))

#Plotting the graph
mosaicplot(Mining_license_vs_Education_table,
           main = "Mosaic plot",
           color = TRUE
)

#Applying chi square test 
print(chisq.test(Mining_license_vs_Education_table, p = p, rescale.p = TRUE))
chisq.test(Mining_license_vs_Education_table)$expected

#(1)Trying the Fisher's exact test (Education v/s Mining License)
#Setting the graph margins
par("mar")
par(mar=c(1,1,1,1))

#Plotting the graph
mosaicplot(Mining_license_vs_Education_table,
           main = "Mosaic plot",
           color = TRUE
)

# Running the fisher test
Mining_license_vs_Education_result <- fisher.test(Mining_license_vs_Education_table)
Mining_license_vs_Education_result
#Finding the p value in the test
Mining_license_vs_Education_result$p.value

#post-hoc test for fisher's exact test
pairwise_fisher_test(as.matrix(Mining_license_vs_Education_table), p.adjust.method = "fdr")


#(2)Trying Chi square test on Mining License v/s Improvements in production practices over the past year
#Creating a new variable that stores the values of 'Improvements in production practices' & 'Mining License' and converting it to a factor

Production_Practices_factor <- factor(c(dataframe$`Improvements in production practices over the past year`))
Mining_License_factor <- factor(c(df$`Mining License`))

class(Mining_License_factor) #Checking the class of Mining License
class(Production_Practices_factor) #Checking the class of Education variable

#Checking number of levels created
nlevels(Mining_License_factor)
nlevels(Production_Practices_factor)

#Viewing the levels created
levels(Mining_License_factor)
levels(Production_Practices_factor)

#Creating a separate dataframe
Mining_license_vs_Improvements_df = data.frame(Mining_License_factor, Production_Practices_factor)
#Creating a contingency table
Mining_license_vs_Improvements_table = table(Mining_License_factor, Production_Practices_factor) 
print(Mining_license_vs_Improvements_table)

#Setting the graph margins
par("mar")
par(mar=c(1,1,1,1))

#Plotting the graph
mosaicplot(Mining_license_vs_Improvements_df,
           main = "Mosaic plot",
           color = TRUE
)

#Applying chi square test 
print(chisq.test(Mining_license_vs_Improvements_table, p = p, rescale.p = TRUE))
chisq.test(Mining_license_vs_Improvements_table)$expected


#(2)Trying the Fisher's exact test (Mining License v/s Improvements over the past year)
#Setting the graph margins
par("mar")
par(mar=c(1,1,1,1))

#Plotting the graph
mosaicplot(Mining_license_vs_Improvements_table,
           main = "Mosaic plot",
           color = TRUE
)
# Running the fisher test
Mining_license_vs_Improvements_result <- fisher.test(Mining_license_vs_Improvements_table)
Mining_license_vs_Improvements_result
#Finding the p value in the test
Mining_license_vs_Improvements_result$p.value

fisher_test(Mining_license_vs_Improvements_table, detailed = TRUE, conf.level = 0.95, conf.int = TRUE)

#Storing the p value in a variable to decide if accept or reject H0
a <- Mining_license_vs_Improvements_result$p.value

if (a <= 0.05) {
  print ("Fail to reject H0")
} else {
  print ("Reject H0")
}

#post-hoc test for fisher's exact test
pairwise_fisher_test(as.matrix(Mining_license_vs_Improvements_table), p.adjust.method = "fdr")

#(3)Trying Chi square test on Mining License v/s Type of training received
#Creating a new variable that stores the values of 'Type of training received' & 'Mining License' and converting it to a factor

Type_of_Training_factor <- factor(c(df$`If yes, please describe the nature of your training.`))
Mining_License_factor <- factor(c(df$`Mining License`))

class(Mining_License_factor) #Checking the class of Mining License
class(Type_of_Training_factor) #Checking the class of Education variable

#Checking number of levels created
nlevels(Mining_License_factor)
nlevels(Type_of_Training_factor)

#Viewing the levels created
levels(Mining_License_factor)
levels(Type_of_Training_factor)

#Creating a separate dataframe
Mining_license_vs_Training_df = data.frame(Mining_License_factor, Type_of_Training_factor)
#Creating a contingency table
Mining_license_vs_Training_table = table(Mining_License_factor, Type_of_Training_factor) 
print(Mining_license_vs_Training_table)

#Setting the graph margins
par("mar")
par(mar=c(1,1,1,1))

#Plotting the graph
mosaicplot(Mining_license_vs_Training_table,
           main = "Mosaic plot",
           color = TRUE
)

#Applying chi square test 
print(chisq.test(Mining_license_vs_Training_table, p = p, rescale.p = TRUE))
chisq.test(Mining_license_vs_Training_table)$expected

#(3)Trying the Fisher's exact test (Mining License v/s Type of training received)
#Setting the graph margins
par("mar")
par(mar=c(1,1,1,1))

#Plotting the graph
mosaicplot(Mining_license_vs_Training_table,
           main = "Mosaic plot",
           color = TRUE
)
# Running the fisher test
Mining_license_vs_Training_result <- fisher.test(Mining_license_vs_Training_table)
Mining_license_vs_Training_result
#Finding the p value in the test
Mining_license_vs_Training_result$p.value

fisher_test(Mining_license_vs_Training_table, detailed = TRUE, conf.level = 0.95, conf.int = TRUE)


# Converting file into Excel
write_xlsx(df, "/Users/yashkarnik/Desktop/University of Surrey/Dissertation/Dataset for Tableau & R1.xlsx")

